name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the version of Node.js you want

      # Step 3: Install pnpm
      - name: Install pnpm
        run: |
          npm install -g pnpm

      # Step 4: Install sharp globally to handle image transformations
      - name: Install sharp
        run: pnpm add sharp

      # Step 5: Install project dependencies using pnpm
      - name: Install dependencies
        run: pnpm install

      # Step 6: Build the project (output to `./dist`)
      - name: Build project
        run: pnpm run build

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
